version: '2'
services:
  mariadb:
    image: 'mysql:8.0'
    ports:
        - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: 'adminpassword'
        MYSQL_DATABASE: 'opensupports'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'adminpassword'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
    - ./database:/var/lib/mysql

  website:
    build: .
    restart: always
    ports:
      - "8080:80"
    volumes:
     - ./config:/config
    depends_on:
      - mariadb
